echo "Step 1"
./Main input/test1.txt input/step1.txt Generalise 6 7 \"n\"
echo "Step 2"
./Main input/step1.txt input/step2.txt Generalise 6 11 \"c\"
echo "Step 3"
./Main input/step2.txt input/step3.txt Rename 6 \"fold\"
echo "Step 4"
./Main input/step3.txt input/step4.txt IntroDef 69 \"sum\"